"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { StoreContextProvider } from "../../components/store-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,1,0"
        />
      </head>
      <StoreContextProvider>
        <body className={inter.className}>{children}</body>
      </StoreContextProvider>
    </html>
  );
}
